receivers:
  otlp: {protocols: {grpc: null, http: null}}
processors:
  batch: null
exporters:
  debug: {verbosity: detailed}
  prometheus: {endpoint: "0.0.0.0:8889"}
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    labels:
      attributes: {service.name: "service_name"}
  jaeger: {endpoint: "jaeger:14250", tls: {insecure: true}}
service:
  pipelines:
    traces: {receivers: [otlp], processors: [batch], exporters: [debug, jaeger]}
    metrics: {receivers: [otlp], processors: [batch], exporters: [debug, prometheus]}
    logs: {receivers: [otlp], processors: [batch], exporters: [debug, loki]}