receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8889"

  # Exporta traces para o Jaeger (via OTLP)
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  # Exporta logs para o Loki (via OTLP)
  otlp/loki:
    endpoint: "http://loki:4318"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/loki]
