receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # Exportador para debug, imprime no console do container
  debug:
    loglevel: info

  # Exportador para Prometheus (métricas)
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Exportador para Loki (logs)
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    labels:
      attributes:
        # Pega o atributo 'service.name' do OTel e o transforma na label 'service_name' do Loki
        service.name: "service_name" 

  # Exportador para Jaeger (traces)
  jaeger:
    endpoint: "jaeger:14250" # Jaeger collector endpoint
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, loki]