name: Test and Deploy API to VPS

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to VPS
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            set -e

            echo ">>> Iniciando deploy na VPS..."
            cd ~/bowlingLanes
            
            echo ">>> Puxando código do repositório..."
            git pull origin main
            
            echo ">>> Parando serviços antigos..."
            docker-compose down
            
            echo ">>> Reconstruindo e subindo os serviços..."
            docker-compose up --build -d
            
            echo ">>> Limpando imagens antigas..."
            docker image prune -f
            
            echo ">>> Deploy finalizado com sucesso!"